[package]
name = "orderbook"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = { version = "0.4", default-features = false }

soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }