[package]
name = "orderbook"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = { version = "0.4", default-features = false }

soroban-sdk = "20.0.0-rc2"

[dev-dependencies]
soroban-sdk = { version = "20.0.0-rc2", features = ["testutils"] }